### ISSUE TITLE
[Feature] Integration card - Part IV - Include devices

### ISSUE THREAD

**Issue by andrewjswan** [homeassistant-extras/device-card#13]
Plz add `include_devices:` to Integration card - We can exclude devices by mask, and so we can add a card that will contain excluded devices, or select, for example, only sockets or lamps.

**Comment by warmfire540** [comment]
so you'd want to exclude entities.. but then include _some_ back..?

**Comment by andrewjswan** [comment]
Sorry `include_devices` I made a mistake when I filled out the Issue. I fixed it... Sorry again.
```Yaml
integration: esphome
include_devices:
 - '*nous*'
 - ...
 - ...
exclude_devices:
 - '*socket*'
```

**Comment by warmfire540** [comment]
@andrewjswan and so `include` will overpower `exclude`?

**Comment by andrewjswan** [comment]
> and so `include` will overpower `exclude`

I think it’s logical, if `include` is specified, then we select what is specified and then from what we selected, we exclude what is specified in `exclude`.

**Comment by warmfire540** [comment]
let me know the new release suffices..
I was able to exclude all my devices, and then include 2 back..

```yaml
type: custom:integration-card
integration: zwave_js
include_devices:
  - 07446f7e31f12e75b412ad0ba9942d32
  - '800*'
exclude_devices:
  - 'Temp*'
  - 'Open*'
  - 'DC*'
  - '800*'
  - 'Double*'
  - 'Tilt*'
  - 'Multi*'
  - 'Indoor*'
  - 'On*'
  - 'Scene*'
  - 'Dry*'
```

**Comment by andrewjswan** [comment]
It's a bit strange, but it works, and I was able to implement what I needed with the following code.
```Yaml
include_devices:
  - "*Nous*"
  - "*Socket*"
  - "*Heater*"
exclude_devices:
  - "*"
```

**Comment by andrewjswan** [comment]
> Any improvements or changes?

Well, this option works, it's just a bit illogical for me. But it's quite possible to use it. For some reason I thought it would be like this (- Jinja equivalent):

only `include_devices` - select(...)
only `exclude_devices` - reject(...)
`include_devices` and `exclude_devices` - select(...) | reject(...)

**Comment by warmfire540** [comment]
@andrewjswan ahh ok.. I can do that...  the way I thought it was explained seemed strange..

so let's do an example..

### Current Behavior Example
Imagine we have an integration with 6 devices:

device_1: "Living Room Light"
device_2: "Kitchen Light"
device_3: "Bedroom Light"
device_4: "Bathroom Light"
device_5: "Outdoor Light"
device_6: "Garage Light"

```yaml
type: custom:integration-card
integration: zwave_js
include_devices:
  - device_1
  - device_2
  - device_3
exclude_devices:
  - device_2
  - device_3
  - device_4
```

In this scenario:
- device_1 is included and not excluded → shown
- device_2 is included but also excluded → the include takes precedence → shown
- device_3 is included but also excluded → the include takes precedence → shown
- device_4 is excluded and not included → not shown
- device_5 is neither included nor excluded → shown (default behavior)
- device_6 is neither included nor excluded → shown (default behavior)

```yaml
type: custom:integration-card
integration: zwave_js
include_devices:
  - device_1
  - device_2
```

today - all devices would show with this setup.. i think lol

### New Behavior Example

```yaml
type: custom:integration-card
integration: zwave_js
include_devices:
  - device_1
  - device_2
  - device_3
exclude_devices:
  - device_2
  - device_3
  - device_4
```

With the proposed logic change:
- First, select devices that match include_devices: devices 1, 2, and 3
- Then, reject any that match exclude_devices: devices 2 and 3 are rejected
- Result: only device_1 is shown

```yaml
type: custom:integration-card
integration: zwave_js
include_devices:
  - device_1
  - device_2
```

here - only 2 devices show
